version: '3'

services:
  postgres-db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=KafkaDbUs3r
      - POSTGRES_PASSWORD=KafkaDbUs3rPwD
      - POSTGRES_DB=kafkaDb

#  kafka:
#    image: 'jmgsoares/apache-kafka:latest'
#    ports:
#      - '9092:9092'
#      - '2181:2181'
#      - '8083:8083'
#    depends_on:
#      - db-server
