package pt.onept.mei.is1920.assignment.kafka.common.enums;

public enum Analytics {
	AVERAGE_EXPENSE_BY_ITEM,
	AVERAGE_EXPENSE_BY_ORDER,
	COUNTRY_HIGHEST_SALES_PER_ITEM,
	EXPENSE_PER_ITEM,
	MOST_PROFITABLE_ITEM,
	PROFIT_PER_ITEM,
	REVENUE_PER_ITEM,
	TOTAL_EXPENSE,
	TOTAL_EXPENSE_LAST_HOUR,
	TOTAL_PROFIT,
	TOTAL_PROFIT_LAST_HOUR,
	TOTAL_REVENUE,
	TOTAL_REVENUE_LAST_HOUR,
	NA
}
